# Generated by Django 4.0.4 on 2022-10-11 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='county',
            name='temperature',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
