# Generated by Django 4.0.4 on 2022-10-11 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop_api', '0002_county_temperature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='county',
            name='K',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='county',
            name='N',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='county',
            name='P',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='county',
            name='humidity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='county',
            name='ph',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='county',
            name='rainfall',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='county',
            name='temperature',
            field=models.FloatField(),
        ),
    ]
