# Generated by Django 4.0.4 on 2022-10-25 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop_api', '0006_csv'),
    ]

    operations = [
        migrations.AddField(
            model_name='csv',
            name='sheet',
            field=models.FileField(default=0, upload_to='media/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='csv',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
