# Generated by Django 4.1.6 on 2023-02-23 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop_api', '0009_prediction_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='image',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crop',
            name='info',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
