# Generated by Django 4.1.6 on 2023-03-16 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop_api', '0011_crop_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='cond',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crop',
            name='fertilizer',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crop',
            name='seeds',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
