# Generated by Django 4.1.6 on 2023-03-16 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop_api', '0012_crop_cond_crop_fertilizer_crop_seeds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='seeds',
        ),
        migrations.AddField(
            model_name='crop',
            name='types',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='crop',
            name='cond',
            field=models.TextField(),
        ),
    ]
