# Generated by Django 4.1.6 on 2023-03-16 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop_api', '0013_remove_crop_seeds_crop_types_alter_crop_cond'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='seedrate',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crop',
            name='spacing',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
